# Shell Component - Modular, highly-optimized shell experience
# All plugins managed by Nix (builtins.fetchGit + nixpkgs). No runtime plugin managers.

{
  lib,
  pkgs,
  config,
  ...
}:
with lib; let
  cfg = config.blackmatter.components.shell;

  # Import shell plugin helper
  shellHelper = import ../lib/shell-helper.nix {inherit lib pkgs;};

  # Import all plugin declarations for zshrc generation
  pluginDecls = [
    (import ./plugins/direnv/direnv/default.nix)
    (import ./plugins/skim-rs/skim/default.nix)
    (import ./plugins/skim-rs/skim-tab-complete/default.nix)
    (import ./plugins/ajeetdsouza/zoxide/default.nix)
    (import ./plugins/atuinsh/atuin/default.nix)
    (import ./plugins/zsh-users/zsh-syntax-highlighting/default.nix)
    (import ./plugins/starship/starship/default.nix)
  ];

  # Generate .zshenv for PATH initialization (loaded before .zshrc)
  # This is critical for direnv to work correctly
  zshenvContent = ''
    # ~/.zshenv - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # This file is loaded FIRST, before .zshrc, for all shells

    # Skip if already sourced
    if [ -n "$__BLACKMATTER_ZSHENV_SOURCED" ]; then return; fi
    export __BLACKMATTER_ZSHENV_SOURCED=1

    # ===== PATH INITIALIZATION =====
    # CRITICAL: Set up PATH before ANY commands are used
    # This ensures direnv, nix, and all tools work correctly

    # Load home-manager session variables (contains environment-specific vars)
    # Always re-evaluate: the HM guard is exported and persists across subshells,
    # which prevents secret files (SOPS) from being read if the first shell ran
    # before secrets were decrypted.
    unset __HM_SESS_VARS_SOURCED
    # Try multiple locations: nix-darwin per-user profile → standalone HM → nix-profile fallback
    if [[ -f "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh" ]]; then
      source "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi

    # Ensure home-manager binaries are in PATH (critical for nix, direnv, etc.)
    export PATH="$HOME/.local/state/nix/profiles/home-manager/home-path/bin:$PATH"

    # Ensure basic system paths are available
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/nix/var/nix/profiles/default/bin:$PATH"

    # Homebrew (when installed) — after system paths, before nix profiles
    # so nix-managed tools always take precedence over brew equivalents
    if [[ -x /opt/homebrew/bin/brew ]]; then
      export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
    elif [[ -x /usr/local/bin/brew ]]; then
      # Intel Mac fallback
      export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
    fi

    # Add user nix profile (highest precedence after HM)
    export PATH="$HOME/.nix-profile/bin:$PATH"

    # ===== SSH TERMINAL FIX =====
    # Force TERM to xterm-256color in SSH sessions. Ghostty's xterm-ghostty
    # terminfo uses extended escape sequences that cause garbled rendering
    # over SSH pty (syntax highlighting, prompt redraw, clear all break).
    # The local Ghostty terminal handles these natively — SSH doesn't.
    if [[ -n "$SSH_CONNECTION" && "$TERM" == "xterm-ghostty" ]]; then
      export TERM=xterm-256color
    fi

    # ===== SHELL CONFIGURATION =====
    # Set shell config paths that must survive direnv's pure environments
    # These are set early so direnv can preserve them
    export STARSHIP_CONFIG="$HOME/.config/shell/plugins/starship/starship/starship.toml"
  '';

  # Shell engine manifest — all sourcing logic is in Rust (bm-shell-engine).
  # Load order: settings → completion → plugins (immediate) → plugins (deferred via precmd)
  #           → editor → aliases → local overrides (scanned) → stale cache cleanup
  shellManifest = shellHelper.mkShellManifest {
    inherit config;
    pluginDecls = pluginDecls;
    preSources = [
      "~/.config/shell/groups/common/settings.zsh"
      "~/.config/shell/groups/completion/init.zsh"
    ];
    postSources = [
      "~/.config/shell/groups/editor/init.zsh"
      "~/.config/shell/groups/aliases/init.zsh"
    ];
    scanDirs = [
      "~/.config/shell/local.d"
    ];
    cleanPaths = [
      "~/.zshrc.zwc"
      "~/.zshenv.zwc"
    ];
  };

  # .zshrc is minimal — all logic lives in the Rust shell engine.
  # Only zsh-specific builtins (bindkey, zmodload, zprof) remain as shell.
  zshrcContent = ''
    # ~/.zshrc - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # NOTE: PATH is set in ~/.zshenv (loaded before this file)
    # NOTE: All sourcing logic is in bm-shell-engine (Rust), not shell.

    # ===== PROFILING (opt-in via ZPROF=1) =====
    [[ -n "$ZPROF" ]] && zmodload zsh/zprof

    # ===== VIM MODE =====
    # Must be set BEFORE plugins so plugin keybindings (atuin ctrl-r, etc.)
    # are not clobbered — bindkey -v resets the viins keymap to defaults.
    bindkey -v

    # ===== SHELL ENGINE (Rust) =====
    # bm-shell-engine reads the manifest, checks file existence, and outputs
    # source commands. Deferred plugins are wrapped in a precmd hook function.
    # Stale .zwc files are cleaned up as a side effect.
    eval "$(${shellHelper.shellEngine}/bin/bm-shell-engine ~/.config/shell/manifest)"

    # ===== PROFILING OUTPUT =====
    [[ -n "$ZPROF" ]] && zprof
  '';

  # Generate .bashrc for bash compatibility (minimal, mainly for tools like Claude Code)
  # This ensures commands run in bash shells have proper tool initialization
  bashrcContent = ''
    # ~/.bashrc - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # Minimal bash configuration for tool compatibility

    # ===== PATH INITIALIZATION =====
    # Load home-manager session variables (always re-evaluate for SOPS secrets)
    unset __HM_SESS_VARS_SOURCED
    if [[ -f "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh" ]]; then
      source "/etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi

    # ===== HOMEBREW (when installed) =====
    if [[ -x /opt/homebrew/bin/brew ]]; then
      export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
    elif [[ -x /usr/local/bin/brew ]]; then
      export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
    fi

    # ===== ZOXIDE INITIALIZATION =====
    # Initialize zoxide for bash (smart directory navigation)
    if command -v zoxide &> /dev/null; then
      eval "$(zoxide init bash --cmd cd)"
    fi

    # ===== BASIC ALIASES =====
    # Only set aliases in interactive shells.
    # BASH_ENV causes this file to be sourced in ALL bash invocations (including
    # non-interactive ones used by tools like Claude Code), so aliasing find/grep/diff
    # to incompatible replacements would silently break script execution.
    if [[ $- == *i* ]]; then
      alias ls='eza --icons --group-directories-first'
      alias ll='eza -l --icons --group-directories-first'
      alias la='eza -la --icons --group-directories-first'
      alias cat='bat --style=plain --paging=never'
      alias grep='rg'
      # Note: find is intentionally NOT aliased (fd flags are incompatible).
      # grep→rg is safe here because the interactive guard above prevents
      # non-interactive scripts from seeing this alias.
    fi
  '';

  # Generate .bash_profile to ensure bashrc is loaded in login shells
  bashProfileContent = ''
    # ~/.bash_profile - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # Ensures .bashrc is loaded in login shells

    # Source .bashrc if it exists
    [[ -f ~/.bashrc ]] && source ~/.bashrc
  '';

in {
  imports = [
    ./plugins/registry.nix # Shell plugin registry with auto-discovery
    ./groups # Shell groups for logical organization
    ./packages # Package management (ecosystem-specific tools)
    ./background # Nord wallpapers
    ./tools # Core tool integrations (jq, direnv)
    ./tmux # Tmux (opt-in, disabled by default)
    ./direnv-lib # Custom direnv use_* functions (use_tend, use_workspace)
  ];

  options.blackmatter.components.shell = {
    enable = mkEnableOption "enable shell component";

    package = mkOption {
      type = types.package;
      default = pkgs.zsh;
      description = "Zsh package to use";
    };
  };

  config = mkIf cfg.enable {
    # Install core packages (Rust-powered CLI tools)
    home.packages = with pkgs;
      [
        cfg.package
        # Core tools (required by aliases, functions, plugins)
        coreutils # GNU wc, sort, cut, etc. — don't rely on macOS /usr/bin
        git
        curl
        (lib.lowPrio python312) # lowPrio: avoids bin/idle conflict with python312.withPackages from nvim LSP
        openssl

        # Core replacements
        bat # Better cat - syntax highlighting
        eza # Better ls - icons, git integration
        fd # Better find - faster, simpler syntax
        ripgrep # Better grep - blazing fast search
        zoxide # Better cd - smart directory jumping
        skim # Fuzzy finder (Rust replacement for fzf)
      ]
      ++ lib.optionals (pkgs ? skim-tab) [ pkgs.skim-tab ] # skim-tab-complete: native fuzzy completion
      ++ [
        atuin # Shell history (Rust replacement for zsh-autosuggestions)

        # Additional Rust power tools
        delta # Better git diff - side-by-side, syntax highlighting
        dust # Better du - disk usage analyzer
        procs # Better ps - modern process viewer
        bottom # Better top/htop - system monitor (btm)
        sd # Better sed - intuitive find & replace
        tokei # Code statistics - lines of code counter
        hyperfine # Command benchmarking

        # Extended Rust power tools
        tealdeer # tldr pages - simplified man pages
        xh # Better curl/httpie - friendly HTTP client
        jaq # Better jq - JSON processor in Rust
        ouch # Better tar/gzip/zip - universal compress/decompress
        hexyl # Better xxd - hex viewer with colors
        choose # Better cut/awk - human-friendly field selection
        difftastic # Structural diff - syntax-aware comparisons
        vivid # LS_COLORS generator with theme support
        mdcat # Markdown renderer for terminal
        pastel # Color manipulation and conversion
        grex # Regex generator from test cases
        macchina # Better neofetch - fast system info
        onefetch # Git repo summary on terminal

        # Network tools (Rust)
        bandwhich # Network bandwidth monitor by process
        trippy # Better traceroute/mtr - network diagnostics
        gping # Graphical ping with chart
        oha # HTTP load generator - wrk/ab replacement
        hurl # HTTP request runner from plain text files

        # Development tools (Rust)
        just # Better make - command runner
        watchexec # File watcher - run commands on changes
        miniserve # HTTP file server - serve directories instantly
        yazi # Terminal file manager - fast and full-featured
        bacon # Background Rust code checker
        cargo-nextest # Better cargo test - parallel, filtered
        mprocs # Run multiple processes in a TUI
        ast-grep # Structural code search/lint via AST patterns
        git-cliff # Changelog generator from conventional commits
        sccache # Shared compilation cache for Rust/C/C++
        typos # Source code spell checker - fast, low false positives

        # Data tools (Rust)
        csvlens # CSV viewer in terminal - interactive
        htmlq # jq for HTML - CSS selector extraction
        fend # Unit-aware calculator - replaces bc/calc
        tailspin # Log file highlighter with auto-detection

        # Disk/cleanup tools (Rust)
        kondo # Disk cleaner - removes node_modules, target/, etc.
        broot # Better tree - interactive file navigator
        ripgrep-all # rg over PDFs, archives, docs, subtitles
        pueue # Task queue daemon - long-running background jobs

        # Development tools
        direnv # Directory-specific environments
        nix-direnv # Better direnv integration for Nix flakes
        starship # Cross-shell prompt
      ]
      ++ lib.optionals (pkgs ? blx) [ pkgs.blx ]
      ++ lib.optionals (pkgs ? bm-syntax) [ pkgs.bm-syntax ]
      ++ lib.optionals (pkgs ? bm-complete) [ pkgs.bm-complete ]
      ++ lib.optionals (pkgs ? bm-shell-engine) [ pkgs.bm-shell-engine ]
      ++ lib.optionals pkgs.stdenv.isLinux [
        gitui # TUI for git (Linux only - uses system libs)
      ];

    # ── Activation: purge all compiled zsh caches on every rebuild ──────────
    # Zsh silently prefers .zwc (compiled wordcode) files over .zsh source.
    # Under Nix, ALL shell config is symlinked to the store, so ANY .zwc
    # from a previous generation is stale by definition. Rather than detect
    # staleness (which is fragile — store symlinks have epoch timestamps),
    # we nuke every .zwc on rebuild and let zsh use the source directly.
    # The performance cost is negligible on modern hardware.
    home.activation.cleanZshCache = lib.hm.dag.entryAfter ["writeBoundary"] ''
      # ── .zwc files under ~/.config/shell/ (plugins + groups) ──
      find "$HOME/.config/shell" -name '*.zwc' -delete 2>/dev/null || true
      find "$HOME/.config/shell" -name '*.zwc.target' -delete 2>/dev/null || true

      # ── .zwc files next to dotfiles (zshrc, zshenv, etc.) ──
      rm -f "$HOME/.zshrc.zwc" "$HOME/.zshenv.zwc" "$HOME/.zprofile.zwc"

      # ── zcompdump: force regeneration so new packages get completions ──
      rm -f "$HOME/.cache/zsh/zcompdump-"*
      rm -f "$HOME/.cache/zsh/zcompdump-"*.zwc

      # ── orphan zcompdump files from old config layouts ──
      rm -f "$HOME/.zcompdump" "$HOME/.zcompdump."*
      rm -f "$HOME/.zsh/zcompdump" "$HOME/.zsh/zcompdump.zwc"
    '';

    # Generate .zshenv (loaded FIRST, before .zshrc)
    # Critical for direnv and all commands to have correct PATH
    home.file.".zshenv".text = zshenvContent;

    # Generate .direnvrc for direnv to inherit correct PATH
    # This ensures direnv subprocesses (like 'use flake') have all commands available
    home.file.".direnvrc".text = ''
      # ~/.direnvrc - Generated by Nix (blackmatter shell component)
      # DO NOT EDIT - Changes will be overwritten
      # This file is loaded by direnv before processing any .envrc files

      # Load nix-direnv (provides optimized use_flake that preserves environment)
      # nix-direnv makes direnv's use of Nix fast and prevents garbage collection
      # https://github.com/nix-community/nix-direnv
      source ${pkgs.nix-direnv}/share/nix-direnv/direnvrc

      # Wrap use_flake to preserve system PATH
      # Rename original function, then create wrapper
      if declare -f use_flake > /dev/null; then
        # Rename the nix-direnv use_flake to _use_flake_nixd env
        eval "$(declare -f use_flake | sed '1s/use_flake/_use_flake_nixdirenv/')"

        # Create new use_flake that preserves PATH
        use_flake() {
          # Save PATH before flake loads
          local saved_path="$PATH"

          # Call original nix-direnv use_flake
          _use_flake_nixdirenv "$@"

          # Extend PATH to include original paths after flake paths
          # This ensures both flake dev packages AND system commands work
          export PATH="$PATH:$saved_path"
        }
      fi
    '';

    # Shell engine manifest (consumed by bm-shell-engine at shell startup)
    xdg.configFile."shell/manifest".text = shellManifest;

    # Generate .zshrc
    home.file.".zshrc".text = zshrcContent;

    # Generate .bashrc for bash compatibility
    home.file.".bashrc".text = bashrcContent;

    # Generate .bash_profile for login shells
    home.file.".bash_profile".text = bashProfileContent;

    # Set BASH_ENV to source bashrc in non-interactive shells
    # This ensures tools like Claude Code that use non-interactive bash get proper initialization
    home.sessionVariables = {
      BASH_ENV = "$HOME/.bashrc";
    };

    # Enable shell groups
    blackmatter.components.shell.groups = {
      enable = true;
      common.enable = true;
      completion.enable = true;
      editor.enable = true;
      aliases.enable = true;
      functions.enable = true;
    };

    # Enable default plugins
    blackmatter.components.shell.plugins = {
      direnv.direnv.enable = mkDefault true;
      skim-rs.skim.enable = mkDefault true;
      skim-rs.skim-tab-complete.enable = mkDefault true;
      ajeetdsouza.zoxide.enable = mkDefault true;
      atuinsh.atuin.enable = mkDefault true;
      zsh-users.zsh-syntax-highlighting.enable = mkDefault true;
      starship.starship.enable = mkDefault true;
    };

    # Keep existing package configuration enabled
    blackmatter.components.shell.packages.enable = true;
    blackmatter.components.shell.background.enable = true;
    blackmatter.components.shell.tools.enable = true;

    # Enable direnv library (custom use_* functions)
    blackmatter.components.shell.direnvLib.enable = mkDefault true;
  };
}
