# Shell Component - Modular, highly-optimized shell experience
# All plugins managed by Nix (builtins.fetchGit + nixpkgs). No runtime plugin managers.

{
  lib,
  pkgs,
  config,
  ...
}:
with lib; let
  cfg = config.blackmatter.components.shell;

  # Import shell plugin helper
  shellHelper = import ../lib/shell-helper.nix {inherit lib pkgs;};

  # Import all plugin declarations for zshrc generation
  pluginDecls = [
    (import ./plugins/direnv/direnv/default.nix)
    (import ./plugins/junegunn/fzf/default.nix)
    (import ./plugins/aloxaf/fzf-tab/default.nix)
    (import ./plugins/ajeetdsouza/zoxide/default.nix)
    (import ./plugins/zsh-users/zsh-autosuggestions/default.nix)
    (import ./plugins/zsh-users/zsh-syntax-highlighting/default.nix)
    (import ./plugins/starship/starship/default.nix)
  ];

  # Generate .zshenv for PATH initialization (loaded before .zshrc)
  # This is critical for direnv to work correctly
  zshenvContent = ''
    # ~/.zshenv - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # This file is loaded FIRST, before .zshrc, for all shells

    # Skip if already sourced
    if [ -n "$__BLACKMATTER_ZSHENV_SOURCED" ]; then return; fi
    export __BLACKMATTER_ZSHENV_SOURCED=1

    # ===== PATH INITIALIZATION =====
    # CRITICAL: Set up PATH before ANY commands are used
    # This ensures direnv, nix, and all tools work correctly

    # Load home-manager session variables (contains environment-specific vars)
    # Try multiple locations (Linux vs Darwin)
    if [[ -f "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi

    # Ensure home-manager binaries are in PATH (critical for nix, direnv, etc.)
    export PATH="$HOME/.local/state/nix/profiles/home-manager/home-path/bin:$PATH"

    # Ensure basic system paths are available
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/nix/var/nix/profiles/default/bin:$PATH"

    # Add user nix profile
    export PATH="$HOME/.nix-profile/bin:$PATH"

    # ===== SHELL CONFIGURATION =====
    # Set shell config paths that must survive direnv's pure environments
    # These are set early so direnv can preserve them
    export STARSHIP_CONFIG="$HOME/.config/shell/plugins/starship/starship/starship.toml"
  '';

  # Generate .zshrc from plugins and groups
  # Load order: settings → completion (compinit) → plugins → editor → aliases → functions
  # Completion must load before fzf-tab plugin; deferred plugins load after first prompt
  zshrcContent = ''
    # ~/.zshrc - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # NOTE: PATH is set in ~/.zshenv (loaded before this file)

    # ===== PROFILING (opt-in via ZPROF=1) =====
    [[ -n "$ZPROF" ]] && zmodload zsh/zprof

    # ===== CORE SETTINGS =====
    # Load core shell settings (must be first)
    [[ -f ~/.config/shell/groups/common/settings.zsh ]] && \
      source ~/.config/shell/groups/common/settings.zsh

    # ===== COMPLETION SYSTEM =====
    # Load completion BEFORE plugins (fzf-tab requires compinit)
    [[ -f ~/.config/shell/groups/completion/init.zsh ]] && \
      source ~/.config/shell/groups/completion/init.zsh

    # ===== PLUGINS (sorted by priority) =====
    ${shellHelper.mkPluginInits pluginDecls config}

    # ===== SHELL GROUPS =====
    # Load editor configuration (vim mode)
    [[ -f ~/.config/shell/groups/editor/init.zsh ]] && \
      source ~/.config/shell/groups/editor/init.zsh

    # Load aliases
    [[ -f ~/.config/shell/groups/aliases/init.zsh ]] && \
      source ~/.config/shell/groups/aliases/init.zsh

    # Load functions (autoloaded on first call)
    [[ -f ~/.config/shell/groups/functions/init.zsh ]] && \
      source ~/.config/shell/groups/functions/init.zsh

    # ===== LOCAL OVERRIDES =====
    # Drop files into ~/.config/shell/local.d/*.zsh for machine-specific aliases,
    # env vars, and tweaks. Each component can write its own file — no conflicts.
    for __bm_local in ~/.config/shell/local.d/*.zsh; do
      [[ -f "$__bm_local" ]] && source "$__bm_local"
    done
    unset __bm_local

    # ===== PERFORMANCE =====
    # Compile all sourced files in background for faster subsequent loads
    {
      for f in ~/.config/shell/{groups,plugins}/**/*.zsh; do
        [[ -f "$f" ]] && [[ ! ''${f}.zwc -nt $f ]] && zcompile "$f"
      done
      [[ ! ~/.zshrc.zwc -nt ~/.zshrc ]] && zcompile ~/.zshrc
    } &!

    # ===== PROFILING OUTPUT =====
    [[ -n "$ZPROF" ]] && zprof
  '';

  # Generate .bashrc for bash compatibility (minimal, mainly for tools like Claude Code)
  # This ensures commands run in bash shells have proper tool initialization
  bashrcContent = ''
    # ~/.bashrc - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # Minimal bash configuration for tool compatibility

    # ===== PATH INITIALIZATION =====
    # Load home-manager session variables
    if [[ -f "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.local/state/nix/profiles/home-manager/home-path/etc/profile.d/hm-session-vars.sh"
    elif [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
      source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi

    # ===== ZOXIDE INITIALIZATION =====
    # Initialize zoxide for bash (smart directory navigation)
    if command -v zoxide &> /dev/null; then
      eval "$(zoxide init bash --cmd cd)"
    fi

    # ===== BASIC ALIASES =====
    # Only set aliases in interactive shells.
    # BASH_ENV causes this file to be sourced in ALL bash invocations (including
    # non-interactive ones used by tools like Claude Code), so aliasing find/grep/diff
    # to incompatible replacements would silently break script execution.
    if [[ $- == *i* ]]; then
      alias ls='eza --icons --group-directories-first'
      alias ll='eza -l --icons --group-directories-first'
      alias la='eza -la --icons --group-directories-first'
      alias cat='bat --style=plain --paging=never'
      # Note: find and grep are intentionally NOT aliased here.
      # fd and rg have incompatible flag syntax with POSIX find/grep,
      # which breaks scripts and tool integrations that rely on standard flags.
      # Use fd/rg directly from the command line when you want them.
    fi
  '';

  # Generate .bash_profile to ensure bashrc is loaded in login shells
  bashProfileContent = ''
    # ~/.bash_profile - Generated by Nix (blackmatter shell component)
    # DO NOT EDIT - Changes will be overwritten
    # Ensures .bashrc is loaded in login shells

    # Source .bashrc if it exists
    [[ -f ~/.bashrc ]] && source ~/.bashrc
  '';

in {
  imports = [
    ./plugins/registry.nix # Shell plugin registry with auto-discovery
    ./groups # Shell groups for logical organization
    ./packages # Keep existing package management
    ./background # Keep existing background component
    ./tools # Keep existing tools
    ./envrc # Keep existing envrc
    ./tmux # Keep existing tmux
  ];

  options.blackmatter.components.shell = {
    enable = mkEnableOption "enable shell component";

    package = mkOption {
      type = types.package;
      default = pkgs.zsh;
      description = "Zsh package to use";
    };
  };

  config = mkIf cfg.enable {
    # Install core packages (Rust-powered CLI tools)
    home.packages = with pkgs;
      [
        cfg.package
        # Core tools (required by aliases, functions, plugins)
        git
        curl
        python312
        openssl

        # Core replacements
        bat # Better cat - syntax highlighting
        eza # Better ls - icons, git integration
        fd # Better find - faster, simpler syntax
        ripgrep # Better grep - blazing fast search
        zoxide # Better cd - smart directory jumping
        fzf # Fuzzy finder

        # Additional Rust power tools
        delta # Better git diff - side-by-side, syntax highlighting
        dust # Better du - disk usage analyzer
        procs # Better ps - modern process viewer
        bottom # Better top/htop - system monitor (btm)
        sd # Better sed - intuitive find & replace
        tokei # Code statistics - lines of code counter
        hyperfine # Command benchmarking

        # Extended Rust power tools
        tealdeer # tldr pages - simplified man pages
        xh # Better curl/httpie - friendly HTTP client
        jaq # Better jq - JSON processor in Rust
        ouch # Better tar/gzip/zip - universal compress/decompress
        hexyl # Better xxd - hex viewer with colors
        choose # Better cut/awk - human-friendly field selection
        difftastic # Structural diff - syntax-aware comparisons
        vivid # LS_COLORS generator with theme support
        mdcat # Markdown renderer for terminal
        pastel # Color manipulation and conversion
        grex # Regex generator from test cases
        macchina # Better neofetch - fast system info
        onefetch # Git repo summary on terminal

        # Network tools (Rust)
        bandwhich # Network bandwidth monitor by process
        trippy # Better traceroute/mtr - network diagnostics
        gping # Graphical ping with chart

        # Development tools (Rust)
        just # Better make - command runner
        watchexec # File watcher - run commands on changes
        miniserve # HTTP file server - serve directories instantly
        yazi # Terminal file manager - fast and full-featured

        # Development tools
        direnv # Directory-specific environments
        nix-direnv # Better direnv integration for Nix flakes
        starship # Cross-shell prompt
      ]
      ++ lib.optionals pkgs.stdenv.isLinux [
        gitui # TUI for git (Linux only - uses system libs)
      ];

    # Generate .zshenv (loaded FIRST, before .zshrc)
    # Critical for direnv and all commands to have correct PATH
    home.file.".zshenv".text = zshenvContent;

    # Generate .direnvrc for direnv to inherit correct PATH
    # This ensures direnv subprocesses (like 'use flake') have all commands available
    home.file.".direnvrc".text = ''
      # ~/.direnvrc - Generated by Nix (blackmatter shell component)
      # DO NOT EDIT - Changes will be overwritten
      # This file is loaded by direnv before processing any .envrc files

      # Load nix-direnv (provides optimized use_flake that preserves environment)
      # nix-direnv makes direnv's use of Nix fast and prevents garbage collection
      # https://github.com/nix-community/nix-direnv
      source ${pkgs.nix-direnv}/share/nix-direnv/direnvrc

      # Wrap use_flake to preserve system PATH
      # Rename original function, then create wrapper
      if declare -f use_flake > /dev/null; then
        # Rename the nix-direnv use_flake to _use_flake_nixd env
        eval "$(declare -f use_flake | sed '1s/use_flake/_use_flake_nixdirenv/')"

        # Create new use_flake that preserves PATH
        use_flake() {
          # Save PATH before flake loads
          local saved_path="$PATH"

          # Call original nix-direnv use_flake
          _use_flake_nixdirenv "$@"

          # Extend PATH to include original paths after flake paths
          # This ensures both flake dev packages AND system commands work
          export PATH="$PATH:$saved_path"
        }
      fi
    '';

    # Generate .zshrc
    home.file.".zshrc".text = zshrcContent;

    # Generate .bashrc for bash compatibility
    home.file.".bashrc".text = bashrcContent;

    # Generate .bash_profile for login shells
    home.file.".bash_profile".text = bashProfileContent;

    # Set BASH_ENV to source bashrc in non-interactive shells
    # This ensures tools like Claude Code that use non-interactive bash get proper initialization
    home.sessionVariables = {
      BASH_ENV = "$HOME/.bashrc";
    };

    # Enable shell groups
    blackmatter.components.shell.groups = {
      enable = true;
      common.enable = true;
      completion.enable = true;
      editor.enable = true;
      aliases.enable = true;
      functions.enable = true;
    };

    # Enable default plugins
    blackmatter.components.shell.plugins = {
      direnv.direnv.enable = mkDefault true;
      junegunn.fzf.enable = mkDefault true;
      aloxaf.fzf-tab.enable = mkDefault true;
      ajeetdsouza.zoxide.enable = mkDefault true;
      zsh-users.zsh-autosuggestions.enable = mkDefault true;
      zsh-users.zsh-syntax-highlighting.enable = mkDefault true;
      starship.starship.enable = mkDefault true;
    };

    # Keep existing package configuration enabled
    blackmatter.components.shell.packages.enable = true;
    blackmatter.components.shell.background.enable = true;
    blackmatter.components.shell.tools.enable = true;
  };
}
